# .github/workflows/build.yml
name: build-and-push-twenty
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---- Build & push server image ----
      - name: Build & push server
        uses: docker/build-push-action@v6
        with:
          context: .
          file: packages/twenty-server/Dockerfile
          push: true
          tags: ghcr.io/brianclark490/twenty-server:main

      # ---- Build & push worker image ----
      - name: Build & push worker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: packages/twenty-worker/Dockerfile
          push: true
          tags: ghcr.io/brianclark490/twenty-worker:main
